### ISSUE TITLE
where can find sample source code?

### ISSUE THREAD

**Issue by combatexe** [uwegeercken/jare#1]
Hi friend,I am interested in this project and want to study,please provide some sample case,such as rule/rule-sets config, app main function,etc... thanks a lot!

**Comment by uwegeercken** [comment]
Sorry for the late reply: the source code is available on github. For the ruleengine itself and the web app. There is also a lot of documentation avbl and a lot of info on my blog: http://datamelt.weebly.com

**Comment by combatexe** [comment]
thank you ,friend !
