### ISSUE TITLE
Improvement: Be able to disable rulegroups/subgroups

### ISSUE THREAD

**Issue by codek** [uwegeercken/jare#3]
It would be nice to be able to easily disable rule groups / sub groups from the UI.

I guess this can be achieved by butchering the valid to date, but something more explicit may be nice!

**Comment by uwegeercken** [comment]
disable in the sense of: will not be exported to the project file? 

As you might have seen, rulegroups might depend on other rulegroups. They are only run depending on the results of another group. If you disable a group that other groups depend on, then this could be an issue.

And then, do you want disabled groups to be hidden in some way from the display and have a separate page to enable them again (similar to how users can be disabled) or do you still want to have them displayed?

But in general I think it is a good idea and doable.

**Comment by codek** [comment]
yes, it's as simple as that. Imagine debugging a huge project, you may want to disable some rules etc.  But yes, if it's depended on then it does add complication, perhaps it has to propagate up or something

**Comment by uwegeercken** [comment]
two points here: if a group depends on another one, then it can not be disabled. the group it depends on should be disabled first.

then if you really have a huge project, you would not want to disable all rulegroups by hand. maybe a search function would be better like in email e.g. and then have some adjustments one can apply to all selected groups, such as modify from/until date, enable/disable, delete, change owner, copy to new project, etc.

**Comment by uwegeercken** [comment]
I have implemented the code. It will require a small database change.

I am testing it now and will soon release the updated version.
