### ISSUE TITLE
Improvement - Save test data

### ISSUE THREAD

**Issue by codek** [uwegeercken/jare#4]
The rule tester is _really_ handy.  However it doesnt save the data. It would be great if at least it saved it for the duration of the session.

It would be even better if it persisted it to the DB.

And what would be amazing, is if you can define optional data sets so you can create multiple test cases for the testing!  (but maybe thats too far!)

**Comment by uwegeercken** [comment]
Saving the test data can be quite tricky I guess, if the rules change. I will have to spend some time on this.

One the last point: Is your idea to provide e.g. CSV files that you test the data against? Or do you want to store the test data (multiple ones) you entered and then have the choice to select one?

**Comment by codek** [comment]
OK that is a good point, needs to be thought out.   Let me have a bit more of a ponder..

**Comment by uwegeercken** [comment]
added functionality to save test data in database. user can also list and delete the test data (delete one per one or delete all).
